[project]
name = "gui-m4b-converter"  # Add a proper name here instead of empty string
version = "0.0.1"
dependencies = [
    "pyqt6>=6.4.0",
    "mutagen>=1.46.0",
    "requests>=2.31.0",
    "ffmpeg-python>=0.2.0",
]
requires-python = ">=3.13"
[tool.uv]
package = false